name: qavenue
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter   
  location: ^4.0.0-nullsafety.0
  permission_handler: ^6.1.1
  app_settings: 4.1.0
  url_launcher: ^6.0.3
  geolocator: ^7.0.1
  flutter_web_browser: "^0.14.0"
  share: ^2.0.1
  android_intent: ^2.0.0
  pull_to_refresh: ^1.6.4
  universal_platform: ^0.1.3
  firebase_dynamic_links: ^0.8.0
  cupertino_icons: ^1.0.0
  flutter_webview_plugin: ^0.3.0
  flutter_offline: ^0.3.0
  intent: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
flutter:  
  assets:     
    - assets/icon/images/logo1.png
    - assets/icon/images/offline_blue.gif
  uses-material-design: true

