name: qavenue
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter   
  location: ^4.0.0-nullsafety.0
  app_settings: 4.1.0
  url_launcher: ^6.0.3
  firebase_messaging: ^5.1.2 
  geolocator: ^7.0.1
  share: ^2.0.1
  cupertino_icons: ^1.0.0
  flutter_webview_plugin: ^0.3.0
  flutter_offline: ^0.3.0
  uni_links: ^0.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
flutter:  
  assets:     
    - assets/icon/images/logo1.png
    - assets/icon/images/offline_blue.gif
  uses-material-design: true

